name: Black

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6.x'
    - name: Install Black
      run: pip install black==19.3b0
    - name: Run Black checker
      run: black --check --diff --exclude=portal/__init__.py .
