name: Run Black linter

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6.x'
    - name: Check Python version
      run: python --version
    - name: Install Black
      run: pip install black
    - name: Run Black checker
      run: black --check portal/
